/**
 * Compress frontend/public/models/* to WebP (max 640px) and rewrite mapping.
 *   node scripts/model-images/compress.mjs
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync, statSync } from 'fs';
import { dirname, join, relative, extname, basename } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const sharp = require('./node_modules/sharp');

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');
const OUT_DIR = join(ROOT, 'frontend/public/models');
const MANIFEST_PATH = join(ROOT, 'scripts/model-images/manifest.json');
const MAPPING_JS = join(ROOT, 'frontend/src/config/modelImages.js');
const SOURCES_PATH = join(ROOT, 'scripts/model-images/sources.json');

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

function toPublicUrl(absPath) {
  return '/' + relative(join(ROOT, 'frontend/public'), absPath).replace(/\\/g, '/');
}

async function compressOne(src) {
  const ext = extname(src).toLowerCase();
  if (ext === '.svg' || ext === '.webp') return src;
  if (!['.jpg', '.jpeg', '.png', '.gif', '.tif', '.tiff'].includes(ext)) return src;

  const dest = src.replace(/\.[^.]+$/, '.webp');
  await sharp(src)
    .rotate()
    .resize({ width: 640, height: 640, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 72, effort: 4 })
    .toFile(dest);

  if (dest !== src && existsSync(src)) unlinkSync(src);
  return dest;
}

async function main() {
  const files = walk(OUT_DIR);
  console.log(`Compressing ${files.length} files…`);
  let i = 0;
  for (const f of files) {
    i++;
    try {
      await compressOne(f);
    } catch (err) {
      console.warn('skip', f, err.message);
    }
    if (i % 25 === 0) process.stdout.write(`\r${i}/${files.length}`);
  }
  process.stdout.write('\n');

  if (!existsSync(MANIFEST_PATH)) {
    console.log('No manifest — skip mapping rewrite');
    return;
  }

  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  const sources = existsSync(SOURCES_PATH) ? JSON.parse(readFileSync(SOURCES_PATH, 'utf8')) : {};

  for (const row of manifest) {
    if (!row.fileBase) continue;
    const dir = join(OUT_DIR, dirname(row.fileBase));
    const base = basename(row.fileBase);
    let found = null;
    if (existsSync(dir)) {
      for (const name of readdirSync(dir)) {
        if (name.replace(extname(name), '') === base) {
          found = join(dir, name);
          break;
        }
      }
    }
    if (found) {
      row.localPath = found;
      row.publicUrl = toPublicUrl(found);
      row.ext = extname(found);
      row.bytes = statSync(found).size;
    }
  }

  const entries = {};
  for (const row of manifest) {
    if (row.publicUrl) entries[row.key] = row.publicUrl;
  }

  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
  writeFileSync(
    MAPPING_JS,
    `/**
 * Auto-generated model product image map.
 * Key: "Brand|Model" → public image URL (/models/... served by frontend).
 * Regenerated by: node scripts/model-images/finalize.mjs + compress.mjs
 */
export const MODEL_IMAGES = ${JSON.stringify(entries, null, 2)};

export function getModelImageUrl(brand, model) {
  if (!brand || !model) return null;
  return MODEL_IMAGES[\`\${brand}|\${model}\`] || null;
}

export function modelImageStats() {
  return { mapped: Object.keys(MODEL_IMAGES).length };
}
`
  );

  const all = walk(OUT_DIR);
  const bytes = all.reduce((s, p) => s + statSync(p).size, 0);
  console.log(
    JSON.stringify(
      {
        mapped: Object.keys(entries).length,
        files: all.length,
        sizeMB: Math.round((bytes / 1024 / 1024) * 10) / 10,
      },
      null,
      2
    )
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
